name: Deploy to Server

on:
  push:
    branches:
      - main # Jalankan workflow setiap kali ada push ke branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Menggunakan versi terbaru

      - name: Deploy and Restart PM2
        uses: appleboy/ssh-action@v1.0.3 # Menggunakan versi terbaru
        with:
          host: 20.214.51.1
          username: 'ihear_fe'
          password: 'Qa04091518@@' # Atau gunakan 'key' untuk SSH key
          script: |
            # 1. Navigasi ke direktori proyek
            # Menggunakan path dari log error Anda untuk akurasi
            echo "🔄 Navigating to project folder..."
            cd /home/ihear_fe/be-bookkeeping

            # 2. Ambil kode terbaru dari Git
            echo "🔄 Pulling latest code from main branch..."
            git pull origin main

            # 3. Install atau update dependencies
            echo "📦 Installing/updating dependencies..."
            npm install

            # 4. Build kode TypeScript menjadi JavaScript
            # Menggunakan `npm run build` sesuai package.json Anda
            echo "🔧 Building TypeScript..."
            npm run build

            # 5. Reload aplikasi menggunakan file ecosystem.config.js
            # INI ADALAH BAGIAN PALING PENTING
            # `startOrReload` akan memulai jika belum ada, atau me-reload jika sudah berjalan.
            # Ini memastikan semua variabel dari env di ecosystem.config.js dimuat.
            echo "🚀 Reloading PM2 application using ecosystem config..."
            pm2 startOrReload ecosystem.config.js

            # 6. Simpan daftar proses PM2
            echo "💾 Saving PM2 process list..."
            pm2 save

            # 7. Tampilkan status PM2 untuk verifikasi di log Actions
            echo "✅ Deployment complete. Current PM2 status:"
            pm2 list
